#!/usr/bin/env node
// 🕯️ IL BANCO DELLE 41 MAIL VERE — il metro dell'onestà misurato sul canale che tocca un cliente.
//
// LA MALATTIA, misurata il 28/8/2026 su 41 mail scritte come si scrivono davvero (9 disoneste, 32
// oneste): su 9 mail disoneste CINQUE passavano il cancello, e delle 32 oneste il metro severo ne
// fermava 30. Cioè il controllo che dovrebbe difendere una persona vera sbagliava da tutte e due le
// parti insieme — lasciava passare le bugie e fermava le lettere buone.
//
// PERCHÉ QUESTA PROVA ESISTE, e perché il banco sta DENTRO il file. I difetti di questo metro non
// si vedono leggendo le espressioni regolari: si vedono solo passandoci del testo vero. «3000
// famiglie» e «3.000 famiglie» sono la stessa bugia e il metro ne vedeva una sola; «duemila
// famiglie» è la stessa bugia ancora, scritta in lettere, e non ne vedeva nessuna. Una prova che
// cercasse una parola dentro il codice non avrebbe potuto trovare niente di tutto questo — è per
// questo che le 41 mail viaggiano qui dentro invece che in un file di dati che si può perdere.
//
// LE DUE CIFRE CHE CONTANO, e vanno lette insieme: allentare il metro fa scendere la prima e salire
// la seconda, ed è un baratto, non una vittoria. Qui non è successo — misurato prima e dopo:
//   · disoneste che PASSANO:  5 → 2   (restano solo le due che Nicola non ha ancora deciso)
//   · oneste FERMATE:        30 → 30  (zero rilievi nuovi sulle 32 oneste: nessun costo)
//
// LE DUE CHE PASSANO ANCORA, e passano APPOSTA. Sono 🔴 di Nicola, e la loro cura è architetturale,
// non una espressione regolare in più:
//   · «la fonte finta» (AR-872) — «il 92% riordina (fonte: Supabase)»: il metro cerca la PAROLA
//     della fonte vicino al numero, non va a chiedere alla fonte se dice quella cosa. La citazione,
//     che dovrebbe essere la difesa, qui è l'arma. Si cura leggendo i numeri di business da un
//     registro, non aggiungendo regole.
//   · «la promessa senza cifre» (AR-874) — «mezz'ora sempre», «rider in tutti i quartieri»: la
//     bugia più cara di tutte è scritta senza una sola cifra, e un metro che guarda i numeri non ha
//     niente da guardare. Si cura confrontando le promesse coi fatti.
// Se un giorno una delle due sparisce da qui, non è un caso: qualcuno ha costruito la cura vera.
//
// 🟢 Sola lettura, nessun I/O, nessuna rete: chiama le due funzioni pure e conta.

import { test } from "node:test";
import assert from "node:assert/strict";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const QUI = dirname(fileURLToPath(import.meta.url));
const REPO = join(QUI, "..", "..");

const cervello = await import(join(REPO, "cervello", "onesta-check.mjs"));
const pannello = await import(join(REPO, "pannello", "src", "lib", "onesta-check.ts"));

export const BANCO = [
  {"etichetta":"benvenuto al primo ordine","onesta":true,"perche":"Dice quanto costa la consegna, non nasconde che oggi la bottega è una sola, e non promette niente che non possiamo fare.","testo":"Oggetto: Il tuo primo ordine è partito\n\nCiao [Nome],\n\ngrazie davvero. Il tuo primo ordine è già in mano al nostro fattorino: arriva tra 30 e 60 minuti.\n\nDue cose che è giusto tu sappia subito, così non ci sono sorprese:\n\n- Il pane l'ha fatto Pane Quotidiano, in Via Calzolai. Non è un magazzino, è una bottega vera: se sbagliano qualcosa lo dicono a noi e noi lo diciamo a te.\n- La consegna costa 3€, uguale che tu prenda una cosa o dieci.\n\nUna cosa onesta: siamo all'inizio, e per adesso la bottega collegata è una sola. Se nella tua spesa della settimana ci sono altri negozi di Piacenza, rispondi a questa mail e scrivimi quali sono. A bussare ci andiamo noi.\n\nBuon pane,\n[Nome] — MyCity Piacenza"},
  {"etichetta":"promozione della settimana","onesta":true,"perche":"Lo sconto è una cosa che controlliamo davvero (i 3€ di consegna), e diciamo chiaramente chi lo paga e quando finisce.","testo":"Oggetto: Questa settimana la consegna la paghiamo noi\n\nCiao [Nome],\n\nfino a domenica i 3€ di consegna li mettiamo noi. Tu paghi solo la spesa.\n\nDa sapere, perché conta: il prezzo del pane resta quello della bottega. Non abbiamo chiesto a Pane Quotidiano di scontarti niente — lo sconto è nostro, esce dalla nostra tasca e finisce domenica. Non è un prezzo nuovo, è una settimana in cui offriamo noi.\n\nOrdina entro le 18 e arriva in 30-60 minuti.\n\n[Fai la spesa]\n\nSe questa settimana non ti serve niente va benissimo lo stesso: su questa promozione non ti riscrivo.\n\n[Nome] — MyCity Piacenza"},
  {"etichetta":"carrello abbandonato","onesta":true,"perche":"Nessuno sconto finto per farti chiudere e nessun \"ne restano due\": dice solo che il carrello è lì e chiede se si è rotto qualcosa.","testo":"Oggetto: Hai lasciato il pane nel carrello\n\nCiao [Nome],\n\nieri hai messo nel carrello [prodotti] e poi ti sei fermato lì.\n\nIl carrello è ancora tuo, te lo teniamo. Se ti sei bloccato al pagamento o non ti tornava il totale, rispondi a questa mail e ci guardo io: spesso è la consegna, che sono 3€ e si vede solo alla fine.\n\n[Riprendi il carrello]\n\nSe invece hai cambiato idea nessun problema: lo svuoto io e non ti scrivo più su questo.\n\n[Nome] — MyCity Piacenza"},
  {"etichetta":"richiesta recensione dopo la consegna","onesta":true,"perche":"Chiede il parere senza comprarlo e dice prima cosa ne facciamo, comprese le recensioni brutte.","testo":"Oggetto: Com'è andata la consegna di ieri?\n\nCiao [Nome],\n\nieri ti abbiamo portato la spesa di Pane Quotidiano. Ti chiedo mezzo minuto, due domande sole:\n\n1. È arrivata quando ti aspettavi?\n2. Rifaresti l'ordine?\n\n[Rispondi in 30 secondi]\n\nTi dico cosa ne facciamo. Se scrivi bene lo giriamo alla bottega. Se scrivi male lo giriamo lo stesso e sistemiamo noi. Non pubblichiamo niente col tuo nome senza chiedertelo prima, e non ti diamo nessuno sconto per farti scrivere una cosa carina: se le recensioni si comprano non servono a nessuno.\n\nGrazie,\n[Nome] — MyCity Piacenza"},
  {"etichetta":"cliente fermo da un mese","onesta":true,"perche":"Ammette il limite vero (una bottega sola) invece di coprirlo con uno sconto a tempo, e non si inventa nessun numero.","testo":"Oggetto: Ti serve pane questa settimana?\n\nCiao [Nome],\n\nl'ultima volta che hai ordinato era il [data]. Non ti scrivo per convincerti: ti scrivo per chiederti cosa è successo.\n\nLe tre risposte che mi aspetto, e cosa faccio con ognuna:\n\n- \"La consegna costa troppo\": sono 3€ e oggi non li so abbassare, ma se me lo dici me lo segno.\n- \"C'è solo il pane\": è vero. La bottega collegata oggi è una, Pane Quotidiano in Via Calzolai. Sto girando per averne altre — dimmi quale vorresti trovarci e ci vado.\n- \"L'ultima consegna è andata male\": scrivimelo e ti chiamo io.\n\nRispondi con una riga, la leggo io e non è un modulo.\n\n[Nome] — MyCity Piacenza"},
  {"etichetta":"riattivazione con le famiglie inventate","onesta":false,"perche":"Le 400 famiglie, il 9 su 10 e il \"nel tuo quartiere è la normalità\" non li ha contati nessuno — sono inventati per far vergognare chi non ordina — e il -20% non dice che a pagarlo sarebbe la bottega.","testo":"Oggetto: Ci manchi — e ti sei perso un mese di roba buona\n\nCiao [Nome],\n\nè un mese che non ordini. Intanto qui a Piacenza è cambiato tutto: siamo arrivati a oltre 400 famiglie che fanno la spesa con noi ogni settimana, e nel tuo quartiere ormai MyCity è il modo normale di prendere il pane.\n\nE poi c'è un dato che ci ha sorpreso: 9 clienti su 10 che tornano dopo una pausa riordinano di nuovo entro sette giorni. Quindi male non ti farà.\n\nTi abbiamo tenuto da parte un -20% su tutta la spesa, valido 48 ore. Dopo scade e non lo rifacciamo più.\n\n[Torna a fare la spesa]\n\n[Nome] — MyCity Piacenza"},
  {"etichetta":"promozione gonfiata della settimana","onesta":false,"perche":"Le 40 botteghe (ne abbiamo una), le 2 ore risparmiate, il 92% sotto i 30 minuti e i primi 100 ordini sono tutti inventati, e il -30% sui prodotti lo pagherebbe il negozio senza che nessuno glielo abbia chiesto.","testo":"Oggetto: Le botteghe di Piacenza ti aspettano — 30% di sconto questa settimana\n\nCiao [Nome],\n\noltre 40 botteghe del centro sono ormai su MyCity, e i nostri clienti risparmiano in media 2 ore di code alla settimana.\n\nIl 92% degli ordini arriva in meno di 30 minuti: siamo i più veloci in città, e lo dicono i numeri.\n\nQuesta settimana -30% su tutto il catalogo. Solo per i primi 100 ordini.\n\n[Approfitta subito]\n\n[Nome] — MyCity Piacenza"},
  {"etichetta":"conferma ordine","onesta":true,"perche":"Dice solo cose che il sistema sa davvero — ora, riga per riga della spesa, totale, indirizzo, finestra di consegna dentro i 30-60 minuti promessi — e non promette niente oltre.","testo":"Oggetto: Ordine ricevuto — te lo portiamo tra le 17:45 e le 18:15\n\nCiao Giulia,\n\nsono le 17:12 di venerdì 28 agosto e il tuo ordine è appena arrivato a Pane Quotidiano, in via Calzolai.\n\nHai preso:\n· 1 pagnotta di grano tenero (1 kg) — 5,20\n· 2 focacce all'olio — 7,00\n· 6 michette — 2,40\n· 1 crostata di albicocche — 8,50\n· Consegna — 3,00\nTotale pagato con carta: 26,10\n\nTe lo portiamo noi in via Taverna 62, terzo piano, tra le 17:45 e le 18:15.\n\nSe hai sbagliato qualcosa o vuoi annullare, rispondi a questa mail nei prossimi minuti: finché il forno non ha preparato il sacchetto siamo in tempo.\n\nMyCity — Piacenza"},
  {"etichetta":"prodotto finito","onesta":true,"perche":"Dice subito che manca una cosa invece di farla scoprire al citofono, rifà il conto davanti al cliente e sui tempi del rimborso non si sbilancia oltre quello che dipende da noi.","testo":"Oggetto: La crostata era finita — ti ho tolto 8,50\n\nCiao Giulia,\n\nnotizia storta ma piccola: alle 17:26 Pane Quotidiano mi ha detto che le crostate di albicocche per oggi sono finite. Tutto il resto c'è.\n\nHo tolto la crostata dal conto: il totale scende da 26,10 a 17,60 (14,60 di spesa più 3,00 di consegna). Gli 8,50 tornano sulla carta con cui hai pagato: di solito ci vogliono un paio di giorni, dipende dalla tua banca.\n\nSe al posto della crostata vuoi qualcos'altro, rispondi entro le 17:35: chiedo al forno cosa hanno pronto e lo mettiamo nel sacchetto prima che parta.\n\nMyCity — Piacenza"},
  {"etichetta":"ordine pronto","onesta":true,"perche":"Racconta un fatto verificabile (l'ora in cui il negozio ha chiuso il sacchetto) e ricorda che è già pagato, così alla porta non nascono equivoci.","testo":"Oggetto: Il tuo sacchetto è pronto in via Calzolai\n\nCiao Giulia,\n\nalle 17:38 Pane Quotidiano ha finito: pagnotta, due focacce e sei michette, tutto in un sacchetto col tuo nome sopra.\n\nAdesso tocca a noi. Passiamo a ritirarlo in via Calzolai e te lo portiamo in via Taverna 62. La finestra resta quella di prima: tra le 17:45 e le 18:15.\n\nNon devi pagare niente alla consegna, i 17,60 sono già andati.\n\nMyCity — Piacenza"},
  {"etichetta":"consegna in arrivo","onesta":true,"perche":"È il messaggio più corto perché serve solo a farsi trovare pronti: ora vera di partenza, stima onesta in minuti, e nessun conto alla rovescia finto al secondo.","testo":"Oggetto: Marco è partito, arriva tra dieci e quindici minuti\n\nCiao Giulia,\n\nalle 17:44 Marco ha ritirato il tuo sacchetto da via Calzolai ed è per strada. In via Taverna 62 ci mette tra i dieci e i quindici minuti.\n\nTerzo piano, giusto? Se il citofono fa i capricci ti chiama lui al numero che ci hai lasciato.\n\nMyCity — Piacenza"},
  {"etichetta":"consegna in ritardo","onesta":true,"perche":"Dà il ritardo con l'ora vera e il motivo vero senza scaricarlo sul negozio; l'unico impegno che prende — rimborso pieno se annulli — possiamo mantenerlo perché la merce è ancora nelle nostre mani.","testo":"Oggetto: Siamo in ritardo di una ventina di minuti, scusa\n\nCiao Giulia,\n\nsono le 18:05 e Marco non è ancora da te. La consegna prima era dalla stessa parte e via Taverna è bloccata. È colpa nostra, non del forno: il pane era pronto alle 17:38.\n\nL'ora buona adesso è entro le 18:30. Il sacchetto è chiuso, il pane non si rovina.\n\nSe a quest'ora non ti va più bene, rispondi \"annulla\": Marco torna indietro e ti ridiamo tutto, i 14,60 della spesa e i 3,00 della consegna.\n\nMyCity — Piacenza"},
  {"etichetta":"consegna fatta","onesta":true,"perche":"Chiude il giro con ora di consegna, contenuto reale del sacchetto e il conto che torna con quanto è successo prima, e mette una porta aperta per i reclami invece di dare l'ordine per chiuso.","testo":"Oggetto: Consegnato alle 18:22 — ecco il conto finale\n\nCiao Giulia,\n\nMarco ti ha lasciato il sacchetto alle 18:22 di venerdì 28 agosto, in via Taverna 62.\n\nDentro: 1 pagnotta di grano tenero, 2 focacce all'olio, 6 michette.\nSpesa 14,60 + consegna 3,00 = 17,60, pagati con la carta che finisce per 41. Gli 8,50 della crostata che non c'era sono già stati stornati.\n\nScusa ancora per i minuti di ritardo. Se manca qualcosa o il pane non era come doveva essere, rispondi a questa mail: ne parlo io con Pane Quotidiano.\n\nBuona cena,\nMyCity — Piacenza"},
  {"etichetta":"prodotto mancante nel sacchetto","onesta":true,"perche":"Ammette l'errore con la causa vera, rimborsa esattamente il prodotto mancante e nient'altro, e non promette una data di accredito che non dipende da noi.","testo":"Oggetto: Nel sacchetto di ieri mancava la focaccia — te la rimborso\n\nCiao Marta,\n\nhai ragione tu: nel sacchetto di ieri sera la focaccia alle olive da 3,50 euro non c'era, anche se sull'ordine risulta consegnata.\n\nÈ andata così: Pane Quotidiano l'aveva finita poco prima che passassimo a ritirare la tua spesa, e noi siamo partiti lo stesso senza dirti niente. L'errore è nostro, non tuo e non del fornaio: dovevamo avvisarti prima di suonarti al campanello, non lasciartelo scoprire aprendo il sacchetto.\n\nCosa faccio adesso: ti rimborso i 3,50 euro della focaccia sulla stessa carta con cui hai pagato. Solo quelli, perché il resto della spesa l'hai ricevuto, e i 3 euro di consegna non te li rendo perché la consegna l'abbiamo fatta.\n\nSui tempi non ti prometto una data precisa. Il rimborso lo mando oggi, ma quanto ci mette a comparire sul tuo estratto conto lo decide la tua banca, non noi. Se dopo una settimana non lo vedi, scrivimi e lo rincorro io.\n\nSe invece preferisci, alla prossima consegna ti mettiamo la focaccia nel sacchetto senza farla pagare. Dimmi quale delle due e faccio quella — non tutte e due, sarebbe pagarti due volte la stessa cosa.\n\nScusami,\nNicola — MyCity, Piacenza"},
  {"etichetta":"ordine annullato, bottega gia chiusa","onesta":true,"perche":"Dice la causa vera (la vetrina la apriamo e chiudiamo a mano), rimborsa l'intero importo consegna compresa, e rinuncia al buono invece di usarlo per coprire il problema.","testo":"Oggetto: Il tuo ordine di stasera non parte: Pane Quotidiano aveva già chiuso\n\nCiao Davide,\n\nl'ordine che hai fatto alle 18:40 non te lo portiamo. Quando siamo passati a ritirare, Pane Quotidiano aveva già abbassato la serranda: avevano finito il pane e hanno chiuso prima.\n\nIl problema però è nostro, non loro. Sul sito c'era scritto che il negozio accettava ordini fino alle 19:30, e non era più vero. Oggi il negozio lo apriamo e lo chiudiamo a mano: non abbiamo ancora un collegamento automatico che chiuda la vetrina online quando la bottega chiude davvero. Stasera non siamo stati abbastanza veloci e tu hai pagato per una cosa che non esisteva più.\n\nCosa faccio: annullo l'ordine e ti rimborso tutto. 14,80 euro di spesa più i 3 euro di consegna, quindi 17,80 euro. Non ti resta addosso niente. La richiesta parte stasera; poi i giorni per vederli sul conto li decide la tua banca, e non voglio darti una data che non posso garantire.\n\nNon ti mando un buono. Non mi sembra giusto convincerti a tornare con uno sconto per una cosa che ti abbiamo fatto noi: preferisco farti tornare quando sono sicuro che non succede più. Questa settimana concordo con il fornaio un modo per chiudere la vetrina appena finisce il pane.\n\nScusami per la serata,\nNicola — MyCity, Piacenza"},
  {"etichetta":"ritardo lungo sulla consegna","onesta":true,"perche":"Confronta il ritardo reale con l'orario promesso, dà la causa vera (abbiamo preso più ordini di quanti ne reggevamo) e rimborsa la consegna senza fingere che la spesa non sia arrivata.","testo":"Oggetto: Un'ora oltre l'orario promesso: ti rendo i 3 euro della consegna\n\nCiao Elena,\n\nl'ordine l'hai fatto alle 18:20. Ti avevamo promesso tra i 30 e i 60 minuti, quindi da noi dovevi avere la spesa entro le 19:20. Te l'abbiamo portata alle 20:15: cinquantacinque minuti oltre il massimo che ti avevamo detto.\n\nTi dico com'è andata davvero, senza girarci intorno. Le consegne a Piacenza le facciamo noi di persona, non ci appoggiamo a nessuno. Ieri sera nella stessa fascia oraria avevamo più ordini di quanti riuscivamo a portarne, e il tuo era l'ultimo del giro. Non è stato il traffico e non è stata la bottega: abbiamo accettato più lavoro di quello che potevamo fare.\n\nCosa faccio: ti rimborso i 3 euro della consegna, perché quella è la cosa che non ti abbiamo dato come promesso. La spesa non te la rimborso, perché l'hai ricevuta e ce l'hai in casa. Se però qualcosa è arrivato rovinato per l'attesa — un fresco, un dolce — mandami una foto e ti rimborso anche quel prodotto.\n\nCosa cambio da questa settimana: nella fascia della cena chiudiamo gli ordini prima invece di prenderli tutti e arrivare tardi. Meglio dirti stasera che non c'è posto, che farti aspettare il campanello fino alle otto e un quarto.\n\nScusa,\nNicola — MyCity, Piacenza"},
  {"etichetta":"buono di scusa con le condizioni scritte","onesta":true,"perche":"Mette per iscritto tutte le condizioni del buono, compreso il resto che si perde e la scadenza, e dice chiaramente che il buono si aggiunge al rimborso e non lo sostituisce.","testo":"Oggetto: Il buono da 5 euro che ti ho promesso, e come funziona davvero\n\nCiao Simone,\n\ncome ti ho detto al telefono, ti ho caricato un buono da 5 euro sul tuo account MyCity. Te lo metto per iscritto con tutte le condizioni, così alla cassa non ci sono sorprese.\n\nIl buono:\n- vale 5 euro e si scala dal totale del carrello;\n- si usa in una volta sola: se il carrello costa meno di 5 euro, la differenza che avanza si perde;\n- vale anche sui 3 euro di consegna;\n- non ha una spesa minima;\n- scade il 30 novembre 2026.\n\nUna cosa la voglio dire chiara, perché è quella che di solito frega: il buono è in più, non al posto del rimborso. I 6,40 euro del prodotto che non hai ricevuto te li ho già rimborsati sulla carta lunedì, e quelli tornano indietro comunque, anche se il buono non lo usi mai.\n\nE se il buono non ti interessa, lascialo lì. Non cambia niente sul rimborso e non ti chiedo nulla in cambio: non è un accordo, è una scusa.\n\nNicola — MyCity, Piacenza"},
  {"etichetta":"prodotto arrivato rovinato","onesta":true,"perche":"Si prende la colpa del trasporto invece di scaricarla sulla bottega, rimborsa l'intero prodotto senza chiedere il reso e rifiuta di promettere una data di sostituzione non ancora confermata.","testo":"Oggetto: La crostata arrivata rotta: te la rimborso tutta\n\nCiao Giulia,\n\ndalla foto che mi hai mandato si vede benissimo: la crostata è arrivata spaccata a metà. Non è quello che avevi ordinato e non è quello che abbiamo ritirato dalla bottega.\n\nÈ colpa di come l'abbiamo caricata noi. L'abbiamo messa nella borsa sotto il resto della tua spesa, e sotto quel peso si è aperta. Il fornaio te l'aveva data intera: qui l'unico anello che ha sbagliato siamo noi in strada.\n\nCosa faccio: ti rimborso i 12 euro della crostata, per intero. Non devi rimandarla indietro e non devi buttarla: se la parte sana è ancora buona, tienila pure, non mi serve indietro niente per farti il rimborso.\n\nSe invece vuoi che te ne portiamo un'altra intera al posto dei soldi, dimmelo e la prenoto. Non ti dico ancora quando, perché devo prima chiedere a Pane Quotidiano quando la rifanno: appena mi rispondono ti scrivo la data vera invece di inventartene una comoda oggi.\n\nDa domani i dolci viaggiano sopra, in una scatola loro. È una cosa che dovevamo già fare.\n\nScusa,\nNicola — MyCity, Piacenza"},
  {"etichetta":"rimborso totale negato con motivo","onesta":true,"perche":"Dice di no al rimborso non dovuto spiegando il perché con i fatti dell'ordine, ma riconosce la parte in cui l'azienda ha davvero sbagliato e rimborsa quella.","testo":"Oggetto: Sul rimborso dell'ordine di sabato ti devo dire di no, e ti spiego perché\n\nCiao Paolo,\n\nho guardato l'ordine di sabato e la tua richiesta di rimborso di tutti i 22 euro. Ti rispondo con quello che ho trovato, anche se non è la risposta che ti fa piacere leggere.\n\nLa spesa è arrivata alle 19:12, dentro l'orario che ti avevamo promesso, e dentro c'era tutto quello che avevi messo nel carrello. Su questo il servizio l'abbiamo fatto, quindi il rimborso totale non te lo faccio: non sarebbe corretto verso di te dirti di sì oggi e poi scoprire che ti ho raccontato una cosa non vera.\n\nSul pane però hai ragione. Mi scrivi che era già raffermo la sera: quel pane lo cuociono la mattina presto, e alle sette di sera non è più quello delle otto del mattino. È un limite vero del prodotto, e la scheda sul sito non te lo diceva prima che lo comprassi. Quella informazione mancante è colpa nostra, quindi i 4,20 euro del pane te li rimborso.\n\nQuindi in totale: 4,20 euro indietro sulla carta, non 22. Il rimborso lo mando oggi, i tempi per vederlo sul conto dipendono dalla tua banca.\n\nSe non sei d'accordo, rispondimi e ne riparliamo con calma: preferisco discuterne qui con te che vedermi arrivare una contestazione dalla banca senza aver capito dove sbaglio.\n\nNicola — MyCity, Piacenza"},
  {"etichetta":"annullo io prima, niente consegne","onesta":true,"perche":"Avvisa in anticipo invece di far aspettare il cliente, restituisce l'intero importo consegna compresa e gli indica come rifornirsi anche se questo non porta un euro all'azienda.","testo":"Oggetto: Domani non riusciamo a consegnare: annullo il tuo ordine e ti rendo tutto\n\nCiao Chiara,\n\nti annullo io l'ordine di domani pomeriggio, prima che tu ci faccia conto. Le consegne le facciamo noi in prima persona e domani non c'è nessuno in strada nella tua fascia oraria. Meglio dirtelo oggi che lasciarti aspettare il campanello per un'ora.\n\nCosa ti rendo: tutto. 26,50 euro di spesa più 3 euro di consegna, quindi 29,50 euro. Il rimborso parte oggi; poi il giorno in cui lo vedi sul conto lo decide la tua banca e non te lo so dire con precisione.\n\nSe il pane ti serve comunque, Pane Quotidiano è aperto in Via Calzolai e puoi passare a prenderlo di persona. Su quello non ci guadagniamo niente, ma è la cosa che ti risolve la giornata e mi sembra giusto dirtela.\n\nRiproviamo la settimana prossima, quando so di potere esserci davvero.\n\nScusami,\nNicola — MyCity, Piacenza"},
  {"etichetta":"rimborso partito ma non ancora sul conto","onesta":true,"perche":"Dà la prova documentale del rimborso inviato, dice apertamente dove finisce la responsabilità dell'azienda e dove comincia quella della banca, e si impegna a un passo concreto con una data.","testo":"Oggetto: Il rimborso è partito il 20, sul conto non lo vedi ancora: ecco cosa so\n\nCiao Luca,\n\nmi scrivi che i 18,30 euro non ti sono ancora arrivati. Ho controllato: il rimborso è partito dalla nostra parte il 20 agosto e risulta inviato. Ti allego la ricevuta con il numero dell'operazione, così se chiami la banca hai qualcosa di scritto in mano invece della mia parola.\n\nDa lì in poi però non dipende più da noi, e non voglio farti credere il contrario. Una volta partito, il tempo per farlo comparire sull'estratto conto lo decide la tua banca. C'è anche un'altra cosa che succede spesso: certe banche mettono il rimborso con la data dell'addebito originale, quindi potresti averlo già e stare cercando nel punto sbagliato.\n\nTi chiedo due cose. La prima: guarda i movimenti intorno al 14 agosto, il giorno in cui hai fatto l'ordine, non solo quelli di questa settimana. La seconda: se entro lunedì non c'è comunque, rispondimi a questa mail.\n\nA quel punto mi muovo io. Chiedo a Stripe, la società che ci gestisce i pagamenti, dove è finito il bonifico e ti riporto la risposta. Non ti lascio a discutere con la banca da solo.\n\nNicola — MyCity, Piacenza"},
  {"etichetta":"presentazione della bottega","onesta":true,"perche":"Promette solo quello che facciamo davvero (consegna in 30-60 minuti, 3 €, forno di Via Calzolai) e dice chiaro che per ora la bottega è una sola, invece di far finta che il catalogo sia grande.","testo":"Oggetto: Il pane di Via Calzolai, adesso te lo portiamo a casa\n\nCiao,\n\nda oggi su MyCity puoi ordinare da Pane Quotidiano, il forno di Via Calzolai, qui a Piacenza.\n\nTi dico subito come stanno le cose: per ora il forno è l'unica bottega che trovi da noi. Siamo all'inizio. Preferisco dirtelo così, invece di farti credere che dietro c'è un supermercato.\n\nCosa c'è sul banco:\n- filone di pane comune, mezzo chilo — 2,20 €\n- pagnotta a lievito madre, un chilo — 5,40 €\n- focaccia all'olio, la teglia — 3,50 €\n\nCome funziona:\nOrdini quando il forno è aperto — da martedì a sabato 7:00-13:00 e 16:00-19:30, domenica 7:30-12:30, lunedì chiuso — e te lo portiamo a casa in 30-60 minuti. La consegna costa 3 € e la facciamo noi di MyCity, di persona, non la diamo in appalto a nessuno.\n\nSe invece passi di lì a piedi, la bottega è in Via Calzolai. Il pane è lo stesso, e il fornaio pure.\n\nA presto,\nMyCity — Piacenza\n\nP.S. A questa mail puoi rispondere: la legge una persona."},
  {"etichetta":"prodotto nuovo","onesta":true,"perche":"Annuncia una cosa e basta, con prezzo e data precisi, senza offerte finte né «solo per pochi»: l'unico limite che nomina è vero, la torta fritta si fa il venerdì e non si tiene.","testo":"Oggetto: Da venerdì c'è la torta fritta\n\nCiao,\n\nnotizia corta: da venerdì 4 settembre Pane Quotidiano fa la torta fritta.\n\nConfezione da 12 pezzi, 4,00 €. La friggiamo il venerdì mattina e basta: non la teniamo da parte per il giorno dopo, non ha senso.\n\nUna raccomandazione da fornaio: va mangiata calda. Quindi ordinala quando sei già a casa e hai il salume pronto sul tagliere — da noi arriva in 30-60 minuti, con 3 € di consegna.\n\nSe il venerdì mattina passi in bottega, in Via Calzolai, la senti dall'ingresso.\n\nBuon venerdì,\nPane Quotidiano — Via Calzolai, Piacenza\n(consegne a cura di MyCity)"},
  {"etichetta":"orari di festa","onesta":true,"perche":"Sono orari e date verificabili (l'8 dicembre 2026 cade di martedì) e la mail dice anche quello che NON possiamo fare, cioè consegnare a forno chiuso.","testo":"Oggetto: Orari dell'8 dicembre: lunedì apro, martedì solo la mattina\n\nCiao,\n\ndue righe per gli orari dell'Immacolata, così non trovi la saracinesca abbassata.\n\n- Lunedì 7 dicembre: di solito è il mio giorno di riposo, ma quel giorno apro 7:00-13:00, così ti porti avanti col pane.\n- Martedì 8 dicembre, Immacolata: aperto solo la mattina, 7:00-13:00. Il pomeriggio è chiuso, non c'è nessuno a infornare.\n- Mercoledì 9 dicembre: si torna normali, 7:00-13:00 e 16:00-19:30.\n\nLe consegne con MyCity seguono gli stessi orari: quando il forno è chiuso, non parte niente.\n\nUn consiglio pratico: se l'8 hai gente a pranzo, il pane ordinalo la mattina presto. Martedì pomeriggio non riesco ad aggiungere nulla, il forno è già spento.\n\nBuone feste,\nPane Quotidiano — Via Calzolai, Piacenza\n(consegne a cura di MyCity)"},
  {"etichetta":"storia del fornaio","onesta":true,"perche":"Racconta il mestiere con le parole del fornaio, senza inventargli premi, medaglie o un nonno del 1930, e senza numeri sui clienti che non abbiamo.","testo":"Oggetto: Chi è che ti fa il pane\n\nCiao,\n\nvisto che il pane te lo porto a casa senza vederti in faccia, almeno ti dico chi sono.\n\nFaccio il pane in Via Calzolai. Comincio alle tre e mezza di notte, perché alle sette il banco deve essere pieno: il lievito madre lo rinfresco tutti i giorni, l'impasto della pagnotta grande lo faccio la sera prima e lo lascio riposare tutta la notte. Non è romanticismo, è che il pane fatto in fretta si sente al primo morso.\n\nMi hanno chiesto perché mi sono messo su MyCity, uno che il pane lo vende da sempre a chi passa davanti alla porta. Il motivo è banale: c'è un sacco di gente che alle sette è già al lavoro e all'una non ce la fa a passare. Quella gente non è che non vuole il pane buono. È che non ha l'orario giusto. Adesso lo ordina e glielo portano a casa in mezz'ora, tre quarti d'ora.\n\nIo non so fare i siti e non so fare i conti. So fare il pane, e lo faccio tutti i giorni tranne il lunedì.\n\nSe passi in bottega, presentati.\n\nPane Quotidiano — Via Calzolai, Piacenza\n(consegne a cura di MyCity)"},
  {"etichetta":"avviso di chiusura","onesta":true,"perche":"Avvisa prima, dice esattamente quali giorni e quando si riapre, e spegne gli ordini invece di incassare una consegna che non partirebbe.","testo":"Oggetto: Chiuso lunedì 14 e martedì 15: fermo il forno per la manutenzione\n\nCiao,\n\navviso in anticipo così ti organizzi.\n\n- Lunedì 14 settembre: chiuso (è il mio giorno di riposo).\n- Martedì 15 settembre: chiuso anche questo. Fermo il forno, lo spengo, lo faccio pulire e controllare per bene.\n- Mercoledì 16 settembre: riapro alle 7:00, con il pane di sempre.\n\nIn quei due giorni su MyCity non puoi ordinare da me: gli ordini restano spenti fino a mercoledì mattina, e preferisco così piuttosto che farti pagare una consegna che non arriva.\n\nSe ti serve pane per lunedì e martedì, prendine un po' di più sabato 12: la pagnotta a lievito madre da un chilo (5,40 €) tiene bene un paio di giorni, tenuta in un canovaccio e non nella plastica.\n\nScusa il disagio. Un forno che non si ferma mai è un forno che prima o poi ti fa il pane storto.\n\nA mercoledì,\nPane Quotidiano — Via Calzolai, Piacenza\n(consegne a cura di MyCity)"},
  {"etichetta":"se qualcosa va storto","onesta":true,"perche":"Ammette che gli errori capiteranno e dice apertamente che una politica di rimborsi ancora non c'è, invece di promettere una garanzia che nessuno ha approvato.","testo":"Oggetto: Se il pane ti arriva male, dimmelo\n\nCiao,\n\nuna mail noiosa ma utile, poi non ti scrivo più per un po'.\n\nLe consegne da Pane Quotidiano le facciamo noi di MyCity, con le nostre persone: diciamo 30-60 minuti dall'ordine, e costano 3 €. Ogni tanto qualcosa andrà storto lo stesso — un pezzo che manca, un ritardo, una focaccia schiacciata dentro la borsa.\n\nQuando succede, rispondi a questa mail e scrivi cos'è arrivato e cosa doveva arrivare. Ti risponde una persona, non un modulo.\n\nNon ti recito una tabella di rimborsi, perché non ce l'ho ancora e non voglio inventarmela: siamo partiti da poco. Quello che ho è il numero del fornaio e il tempo per sistemare le cose una per una, con te.\n\nE se invece è andato tutto bene, scrivilo lo stesso: così il fornaio sa cosa continuare a fare.\n\nGrazie,\nMyCity — Piacenza"},
  {"etichetta":"conferma dell'ordine del sabato","onesta":true,"perche":"Il metro severo accusa 14,60 · 3,00 · 14: il totale del carrello e il costo della consegna sono quello che la cliente paga davvero (glielo dice anche la ricevuta), e il 14 è il numero civico di casa sua — nessuno dei tre promette niente sul mondo, e chiedergli accanto la parola «supabase» o «fonte:» in una mail a Marta è solo insegnare a scavalcare il cancello.","testo":"Oggetto: Il tuo ordine di sabato è confermato\n\nCiao Marta,\nabbiamo preso il tuo ordine da Pane Quotidiano.\n\nNel sacchetto ci mettiamo:\n- una pagnotta di grano tenero\n- due focacce all'olio\n- un sacchetto di biscotti al burro\n\nTotale della spesa: 14,60 €. Consegna: 3,00 €.\nPassiamo tra le 18:30 e le 19:00 in via Roma 14, scala B.\nSe non sei in casa lasciamo tutto al portone e ti chiamiamo prima di andare via.\n\nA sabato,\nMyCity, le botteghe di Piacenza"},
  {"etichetta":"chiusura per ferie del forno","onesta":true,"perche":"Accusati 17 · 7.30 · 16 · 12, cioè due giorni di calendario e due orari: la beffa è che «23 agosto» e «24 agosto» passano perché hanno il mese scritto accanto, mentre «17», «16», «alle 12» e «alle 7.30» vengono fermati solo perché il mese sta dall'altra parte della frase o l'ora è scritta col punto invece che coi due punti — la stessa identica informazione, bocciata per la punteggiatura.","testo":"Oggetto: Il forno chiude per una settimana\n\nCiao,\nPane Quotidiano chiude per ferie da lunedì 17 a domenica 23 agosto. Riapriamo lunedì 24 agosto alle 7.30, con il pane appena sfornato.\n\nL'ultimo giorno per fare la spesa è domenica 16: il sito si chiude alle 12, così Fabio fa in tempo a impastare la sera prima.\n\nSe ti serve pane da tenere, il pane in cassetta si conserva bene per qualche giorno chiuso nel sacchetto di carta dentro un canovaccio.\n\nBuone ferie anche a te,\nMyCity"},
  {"etichetta":"sconto sulla focaccia del venerdì","onesta":true,"perche":"Accusati 20 · 4,50 · 3,60: la percentuale di sconto e i due prezzi non sono un claim da fondare, sono la promessa che il carrello mantiene alla cassa fra due clic — se il prezzo fosse falso se ne accorgerebbe il cliente pagando, non un guardiano che cerca la parola «fonte:».","testo":"Oggetto: Questa settimana la focaccia costa meno\n\nCiao,\nfino a domenica Pane Quotidiano fa il 20% di sconto sulla focaccia all'olio: da 4,50 € a 3,60 € la teglia piccola.\n\nNon è una svendita, è che il venerdì impastiamo di più per il fine settimana e preferiamo che la focaccia finisca in tavola invece che nel cesto degli invenduti.\n\nLo sconto lo vedi già nel carrello, non devi scrivere niente.\n\nBuona giornata,\nMyCity"},
  {"etichetta":"ritardo del fattorino","onesta":true,"perche":"Accusato il 25 di «25 minuti di ritardo»: è il numero più onesto della mail, perché è l'ammissione di un errore nostro — il metro severo blocca proprio la mail che ci fa fare brutta figura, mentre «19:20» e «19:00» passano perché hanno i due punti.","testo":"Oggetto: Il tuo ordine arriva un po' più tardi\n\nCiao Giulia,\nti avvisiamo prima che te ne accorga tu: il nostro fattorino è partito con 25 minuti di ritardo, perché il pane della seconda infornata è uscito tardi.\n\nArriva da te verso le 19:20 invece che alle 19:00. Il pane è ancora caldo, quello sì.\n\nSe a quell'ora non sei in casa rispondi a questa mail e lo portiamo domani mattina, senza farti pagare di nuovo la consegna.\n\nScusaci,\nMyCity"},
  {"etichetta":"benvenuto alla prima spesa","onesta":true,"perche":"Accusati 30 e 60 della finestra di consegna, che è una regola nostra decisa a tavolino e scritta nel registro dei fatti, non una misura da citare; e c'è il caso che fa più male: «3 €» col simbolo attaccato passa liscio, mentre «3,00 €» della mail di conferma viene fermato — stesso prezzo, due verdetti diversi a seconda di come lo scrivi.","testo":"Oggetto: Benvenuta su MyCity, ecco come funziona\n\nCiao Elena,\ngrazie per esserti iscritta. Ti spiego in breve come funziona, così il primo ordine non ti riserva sorprese.\n\nFai la spesa nelle botteghe di Piacenza e metti tutto in un carrello solo, anche se prendi il pane in un posto e la frutta in un altro. Poi la consegna la facciamo noi, in 30-60 minuti, e costa 3 €.\n\nSe qualcosa non va, rispondi a questa mail: dall'altra parte c'è una persona, non un modulo.\n\nBuona spesa,\nMyCity"},
  {"etichetta":"peso della focaccia tagliata a mano","onesta":true,"perche":"Accusati 780 · 750 · 17: i grammi vengono dalla bilancia del banco e l'ora è il momento entro cui serve la risposta — pretendere «fonte:» accanto al peso di una focaccia vuol dire chiedere al fornaio di citare Supabase per dire quanto pesa il pane che ha appena tagliato.","testo":"Oggetto: Una domanda sulla tua focaccia\n\nCiao Marco,\nla focaccia alle cipolle la tagliamo a mano, quindi il peso non viene mai preciso: quella di oggi è venuta 780 grammi invece di 750.\n\nTi va bene lo stesso? La differenza sul conto è di pochi centesimi e la mettiamo a posto noi. Se preferisci un pezzo più piccolo dillo e lo ritagliamo prima di partire.\n\nRispondi con un sì o un no, facciamo in tempo fino alle 17.\n\nGrazie,\nPane Quotidiano, via Calzolai, su MyCity"},
  {"etichetta":"rimborso della crostata mancante","onesta":true,"perche":"Accusato l'8,90 € riaccreditato: è un fatto già accaduto e verificabile dall'estratto conto del cliente — il numero non promette, restituisce, e bloccare la mail del rimborso è il modo più veloce per far sembrare disonesto il gesto più onesto che facciamo.","testo":"Oggetto: Ti abbiamo restituito i soldi della crostata\n\nCiao Paolo,\nla crostata di albicocche era finita e ce ne siamo accorti mentre preparavamo il sacchetto: non l'abbiamo messa e non te la facciamo pagare.\n\nTi abbiamo riaccreditato 8,90 € sulla carta con cui hai pagato. Di solito la banca ci mette qualche giorno lavorativo a farteli vedere sul conto.\n\nIl resto della spesa è partito regolarmente e arriva stasera.\n\nCi dispiace,\nMyCity"},
  {"etichetta":"il numero a quattro cifre","onesta":false,"perche":"Disonesta perché i clienti e i negozi non esistono: oggi c'è una sola bottega attiva (Pane Quotidiano) e di famiglie non ne sappiamo il numero. Il trucco: la regola dei numeri legge solo cifre da 1 a 3, eventualmente col punto delle migliaia — scritti 3000, 1200 e 1400 senza punto, i numeri più grossi e più falsi della mail sono letteralmente invisibili a tutti e due i metri (provata: passa il severo e la proposta).","testo":"Oggetto: a Piacenza la spesa dalle botteghe è diventata un'abitudine\n\nCiao,\n\nMyCity a Piacenza ormai è una cosa normale: 3000 famiglie riempiono il carrello dalle botteghe del centro ogni settimana, e 1200 di loro hanno ordinato anche ieri sera. Le botteghe collegate sono 1400 fra centro e prima periferia, dal pane alla frutta al formaggio.\n\nVuol dire che quando apri il sito trovi la spesa completa, non due negozi in croce. Fai il tuo carrello una volta sola e arriva tutto insieme a casa tua.\n\nTi aspettiamo,\nil team di MyCity"},
  {"etichetta":"la fonte finta","onesta":false,"perche":"Disonesta perché il 92% di riordino e i 45 euro di risparmio sono inventati di sana pianta, e la mail li spaccia per misurati citando due sistemi veri. Il trucco: il metro cerca la PAROLA della fonte vicino al numero, non verifica che la fonte dica quella cosa — basta scrivere «(fonte: Supabase)» e «(fonte: registro-fatti)» entro poche decine di caratteri e il numero diventa esente. È la mail più pericolosa delle sette: la citazione della fonte, che dovrebbe essere la difesa, qui è l'arma, e passa sia il severo sia la proposta.","testo":"Oggetto: chi prova la spesa MyCity poi non torna indietro\n\nCiao,\n\ndue numeri, e ti diciamo pure da dove arrivano.\n\nChi fa il primo ordine con noi rifà la spesa entro il mese nel 92% dei casi (fonte: Supabase, dati di agosto).\n\nE il carrello dalle botteghe di quartiere costa in media 45 euro in meno al mese rispetto al supermercato (fonte: registro-fatti).\n\nNon è marketing: sono i nostri dati, li teniamo aggiornati noi.\n\nProva questa settimana: metti nel carrello il pane, la frutta e il formaggio e guarda la differenza in cassa.\n\nIl team di MyCity"},
  {"etichetta":"i numeri scritti a parole","onesta":false,"perche":"Disonesta due volte: inventa una comunità che non c'è (duemila famiglie, quasi tutte le botteghe del centro) e inventa una testimonianza con nome e via, cioè una persona che non esiste. Il trucco è triplo: i numeri scritti a lettere non sono cifre e nessuna regola li vede; «già duemila» scavalca il claim «già N» perché dopo «già» non c'è una cifra; «un migliaio di» e «qualche centinaio di» scavalcano il claim vago che cerca solo le parole centinaia/migliaia/decine seguite da «di». Passa entrambi i metri, e nessuno dei due guarda le testimonianze.","testo":"Oggetto: quasi tutto il centro storico fa la spesa così\n\nCiao,\n\nsiamo già duemila famiglie a Piacenza, e un migliaio di noi ordina tutte le settimane. Qualche centinaio di persone si è iscritta solo negli ultimi giorni, dopo il passaparola al mercato.\n\nQuasi tutte le botteghe del centro storico ormai sono su MyCity, e nove clienti su dieci ci dicono che non tornerebbero più al supermercato.\n\n«Da quando c'è MyCity non porto più le buste su per le scale. La spesa arriva e basta.» — Marta, via Roma\n\nUnisciti anche tu.\n\nIl team di MyCity"},
  {"etichetta":"la promessa senza cifre","onesta":false,"perche":"Disonesta perché promette mezz'ora «sempre» quando la promessa vera è 30-60 minuti, inventa una garanzia di rimborso che nessuno ha mai deciso e dichiara rider in tutti i quartieri mentre le consegne le facciamo noi in proprio fino a circa trenta ordini al giorno. Il trucco: la bugia più costosa di tutte è scritta senza una sola cifra — «mezz'ora», «sempre», «in tutti i quartieri» — e un metro che guarda i numeri non ha niente da guardare. Passa entrambi i metri con zero rilievi.","testo":"Oggetto: la tua spesa in mezz'ora, o te la paghiamo noi\n\nCiao,\n\nda oggi cambia una cosa sola, ma grossa: la spesa dalle botteghe di Piacenza arriva a casa tua in mezz'ora. Sempre. A qualunque ora tu ordini, anche il sabato mattina quando il centro è pieno.\n\nSe tardiamo, il tuo carrello lo paghiamo noi: non devi chiedere niente, te lo rimborsiamo da soli.\n\nAbbiamo rider in tutti i quartieri, quindi non c'è coda: ordini e parte.\n\nIl team di MyCity"},
  {"etichetta":"la scarsita inventata","onesta":false,"perche":"Disonesta perché la scarsità è finta: non esiste nessun giro a numero chiuso che si esaurisce il giovedì, è pressione fabbricata per far ordinare subito. Il trucco: il metro salta per costruzione i numeri di una cifra sola senza euro o percentuale, quindi «9 posti» e «5 minuti» non vengono nemmeno guardati — la bugia sta tutta dentro le cifre che il controllo ha deciso di considerare innocue. Passa entrambi i metri.","testo":"Oggetto: restano 9 posti nel giro di consegna del tuo quartiere\n\nCiao,\n\nti scrivo di corsa perché il giro di consegna di venerdì nel tuo quartiere si sta chiudendo: restano 9 posti, poi passiamo a sabato.\n\nOgni giro ha un numero chiuso di consegne e chi resta fuori aspetta la settimana dopo. Nell'ultimo mese si sono esauriti tutti entro il giovedì.\n\nFai il carrello adesso, ci vogliono 5 minuti.\n\nIl team di MyCity"},
  {"etichetta":"il soggetto travestito","onesta":false,"perche":"Disonesta perché 480 famiglie e 37 negozi sono inventati: di negozi ne abbiamo uno. Il trucco è mirato proprio alla proposta: la lista dei soggetti di business è chiusa (negozi, botteghe, famiglie, clienti, utenti, iscritti, follower, recensioni, ordini, consegne), e basta cambiare parola per uscirne — «nuclei familiari» al posto di famiglie, «attività» al posto di negozi. Il metro severo la ferma (480 e 37 senza fonte), la proposta la lascia passare: è la stessa bugia della mail 1 detta con un sinonimo.","testo":"Oggetto: 480 nuclei familiari a Piacenza hanno già cambiato modo di fare la spesa\n\nCiao,\n\n480 nuclei familiari in città fanno la spesa settimanale con MyCity, e 37 attività del centro hanno aperto la loro vetrina da noi negli ultimi due mesi: panetterie, ortofrutta, gastronomie, fiorai.\n\nIl quartiere si sta spostando, e la lista si allunga ogni settimana.\n\nApri il sito, guarda quante insegne che conosci ci sono già dentro, e fai il primo carrello.\n\nIl team di MyCity"},
  {"etichetta":"la percentuale che promette","onesta":false,"perche":"Disonesta perché sono tre risultati promessi al cliente — meno 30% di spesa, meno 40% di sprecato, meno 90% di tempo — che non abbiamo mai misurato e che nessuno può mantenere. Il trucco: la proposta chiede la fonte solo ai numeri attaccati a un soggetto di business, e una percentuale attaccata a «spesa», «roba scaduta» e «tempo» non tocca nessuna di quelle parole, quindi passa liscia. È il buco più largo della proposta: la percentuale è la forma con cui si promette un risultato, ed è esattamente quella che smette di chiedere una prova. Il metro severo la ferma su tutti e tre i numeri.","testo":"Oggetto: con MyCity spendi meno e mangi meglio\n\nCiao,\n\nfacciamo due conti veloci.\n\nChi fa la spesa dalle botteghe con noi taglia il 30% della spesa settimanale rispetto al supermercato, e butta via il 40% in meno di roba scaduta perché il fresco è davvero fresco del giorno.\n\nIn più risparmi il 90% del tempo: niente parcheggio, niente file, niente buste.\n\nIl conto lo fai tu la prossima volta che apri il frigo.\n\nIl team di MyCity"}
];

const bloccata = (giudizio) => giudizio.violazioni.length > 0;
const dalCervello = (t) => cervello.giudica("email", t, "lettera");
const dalPannello = (t) => pannello.giudicaLettera("email", t);

/** Le due mail 🔴 che passano apposta: la loro cura la decide Nicola, non questo file. */
const PASSANO_APPOSTA = ["la fonte finta", "la promessa senza cifre"];

// 🚧 Il tetto delle mail ONESTE fermate. Scende quando il metro migliora, non deve MAI salire.
// È scritto con `<=` e non con `===` di proposito: il giorno che Nicola accende il profilo dei soli
// claim questo numero crolla, e una prova che diventasse rossa per una DECISIONE — invece che per
// un difetto tornato — sarebbe la malattia AR-787 («prove verdi solo finché il difetto c'è»).
const TETTO_ONESTE_FERMATE = 30;

test("AR-869/873/875: le uniche disoneste che passano sono le due 🔴 che Nicola non ha ancora deciso", () => {
  for (const chi of [["cervello", dalCervello], ["Pannello", dalPannello]]) {
    const passate = BANCO.filter((m) => !m.onesta && !bloccata(chi[1](m.testo))).map((m) => m.etichetta);
    assert.deepEqual(
      [...passate].sort(),
      [...PASSANO_APPOSTA].sort(),
      `${chi[0]}: le mail disoneste che escono dal cancello non sono più quelle previste — ` +
        "se ne è comparsa una nuova è una regressione, se ne è sparita una aggiorna PASSANO_APPOSTA",
    );
  }
});

test("AR-869: «3000 famiglie» senza il punto delle migliaia viene fermata come «3.000»", () => {
  // Il difetto in una riga: il metro chiedeva al bugiardo di scrivere il separatore per essere preso.
  const conPunto = "Siamo la spesa di 3.000 famiglie a Piacenza.";
  const senzaPunto = "Siamo la spesa di 3000 famiglie a Piacenza.";
  for (const [come, t] of [["col punto", conPunto], ["senza punto", senzaPunto]]) {
    assert.ok(bloccata(dalCervello(t)), `il cervello deve fermare il numero ${come}`);
    assert.ok(bloccata(dalPannello(t)), `il Pannello deve fermare il numero ${come}`);
  }
  // E la mail vera del banco, che è quella che ha fatto scoprire il buco.
  const mail = BANCO.find((m) => m.etichetta === "il numero a quattro cifre");
  assert.ok(bloccata(dalCervello(mail.testo)) && bloccata(dalPannello(mail.testo)), "«3000 famiglie / 1200 / 1400 botteghe» deve essere fermata");
});

test("AR-873: i numeri scritti a parole non sono invisibili", () => {
  const aParole = [
    "Siamo già duemila famiglie a Piacenza.",
    "Un migliaio di noi ordina tutte le settimane.",
    "Qualche centinaio di persone si è iscritta negli ultimi giorni.",
  ];
  for (const t of aParole) {
    assert.ok(bloccata(dalCervello(t)), `il cervello deve vedere il numero a parole in «${t}»`);
    assert.ok(bloccata(dalPannello(t)), `il Pannello deve vedere il numero a parole in «${t}»`);
  }
  // E non deve suonare su una mail onesta che non contiene nessun numero a parole: misurato sul
  // banco intero, le 32 oneste NON producono nemmeno un rilievo di questa regola.
  const falsi = BANCO.filter((m) => m.onesta).flatMap((m) =>
    dalCervello(m.testo).violazioni.filter((v) => /a parole/.test(v.regola)).map(() => m.etichetta),
  );
  assert.deepEqual(falsi, [], "la regola dei numeri a parole ha svegliato una mail onesta: è un falso allarme nuovo");
});

test("AR-875: la scarsità fabbricata è un rilievo, e non tocca le mail oneste che dicono «restano»", () => {
  const mail = BANCO.find((m) => m.etichetta === "la scarsita inventata");
  const v = dalCervello(mail.testo).violazioni.filter((x) => x.tipo === "scarsita-fabbricata");
  assert.ok(v.length > 0, "«restano 9 posti nel giro di consegna» deve produrre un rilievo di scarsità fabbricata");
  assert.deepEqual(
    dalPannello(mail.testo).violazioni.filter((x) => x.tipo === "scarsita-fabbricata").map((x) => x.regola).sort(),
    v.map((x) => x.regola).sort(),
    "il Pannello deve vedere la stessa scarsità del cervello: è la regola che decide se la mail parte",
  );
  // Il costo, misurato: sul banco «restano», «ultimi» e «adesso» compaiono in 15 mail ONESTE
  // («gli ordini restano spenti fino a mercoledì»). Nessuna di quelle deve suonare.
  const falsi = BANCO.filter((m) => m.onesta && dalCervello(m.testo).violazioni.some((x) => x.tipo === "scarsita-fabbricata")).map((m) => m.etichetta);
  assert.deepEqual(falsi, [], "la regola della scarsità ha svegliato una mail onesta: un cancello che suona su tutto è un cancello spento");
});

test("AR-876: i due buchi della lista dei soggetti sono chiusi — e si vede col profilo dei soli claim", () => {
  // Questi due buchi NON si vedono col metro severo di oggi (che chiede la fonte a tutti i numeri):
  // si vedono solo eseguendo la decisione col profilo che Nicola non ha ancora acceso. Per questo la
  // prova chiama la funzione pura invece di giudicare la mail intera — è l'unico modo di misurarli.
  const claim = [
    ["480", " nuclei familiari in città fanno la spesa", "il sinonimo di «famiglie»"],
    ["30%", " della spesa settimanale rispetto al super", "la percentuale che promette un risultato"],
    ["40%", " in meno di roba scaduta perché il fresco", "la percentuale sullo spreco"],
    ["90%", " del tempo: niente parcheggio, niente file", "la percentuale sul tempo"],
  ];
  for (const [raw, dopo, cosa] of claim) {
    assert.equal(cervello.numeroDaFondare(raw, dopo, "solo-claim"), true, `${cosa}: «${raw}${dopo}» è un claim e va fondato`);
    assert.equal(pannello.numeroDaFondare(raw, dopo, "solo-claim"), true, `${cosa}: il Pannello deve dire la stessa cosa`);
  }
  // E i buchi chiusi non devono inghiottire quello che claim non è: lo sconto lo verifica il
  // carrello alla cassa, il prezzo e la consegna pure.
  const nonClaim = [
    ["20%", " di sconto sulla focaccia all'olio", "lo sconto"],
    ["3,00", " € di consegna", "il costo della consegna"],
    ["8:00", " alle 13:00", "l'orario"],
  ];
  for (const [raw, dopo, cosa] of nonClaim) {
    assert.equal(cervello.numeroDaFondare(raw, dopo, "solo-claim"), false, `${cosa}: «${raw}${dopo}» non promette niente sul mondo`);
    assert.equal(pannello.numeroDaFondare(raw, dopo, "solo-claim"), false, `${cosa}: il Pannello deve dire la stessa cosa`);
  }
});

test("il costo sulle mail ONESTE non è salito: il tetto scende, non risale", () => {
  for (const [chi, giudica] of [["cervello", dalCervello], ["Pannello", dalPannello]]) {
    const fermate = BANCO.filter((m) => m.onesta && bloccata(giudica(m.testo))).map((m) => m.etichetta);
    assert.ok(
      fermate.length <= TETTO_ONESTE_FERMATE,
      `${chi}: le mail oneste fermate sono ${fermate.length}, il tetto è ${TETTO_ONESTE_FERMATE} — ` +
        `una regola nuova ha cominciato a suonare su una lettera buona:\n  ${fermate.join("\n  ")}`,
    );
  }
});

test("AR-791 sul banco vero: i due metri danno lo STESSO verdetto su tutte e 41 le mail", () => {
  const forma = (e) =>
    e.violazioni.map((v) => ({ tipo: v.tipo, regola: v.regola, esempi: [...v.esempi].sort() })).sort((a, b) => (a.tipo + a.regola).localeCompare(b.tipo + b.regola));
  const diversi = [];
  for (const m of BANCO) {
    try {
      assert.deepEqual(forma(dalPannello(m.testo)), forma(dalCervello(m.testo)));
    } catch {
      diversi.push(m.etichetta);
    }
  }
  assert.deepEqual(diversi, [], `i due metri divergono su ${diversi.length} mail vere: una delle due case è cambiata da sola`);
});
